apiVersion: v1
kind: Service
metadata:
  name: k8s-service-echo
  namespace: k8s-discord
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  selector:
    app: microservice-echo
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 7001
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-echo
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: microservice-echo

  template:
    metadata:
      labels:
        app: microservice-echo
    spec:
      containers:              
        - name: microservice-echo
          image: <DOCKER_USER>/microservices-echo:<TAG>
          env:
            - name: INGRESS_HOST
              value: "http://<INGRESS_IP>/"
            - name: MICROSERVICE_PORT
              value: "7001"
          ports: 
            - containerPort: 7001
          readinessProbe:
            httpGet:
              path: /echo/health
              port: 7001
            initialDelaySeconds: 5
            periodSeconds: 5
