apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: k8s-stress-lb-backendconfig
  namespace: k8s-discord
spec:
  timeoutSec: 610
---

apiVersion: v1
kind: Service
metadata:
  name: k8s-lb-stress
  namespace: k8s-discord
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
    cloud.google.com/backend-config: '{"default": "k8s-stress-lb-backendconfig"}'
spec:
  selector:
    app: microservice-stress
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 7006
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-stress
  namespace: k8s-discord
spec:
  replicas: 3
  selector:
    matchLabels:
      app: microservice-stress
  template:
    metadata:
      labels:
        app: microservice-stress
    spec:
      containers:
        - name: microservice-stress
          image: <DOCKER_USER>/microservices-stress:<TAG>
          env:
            - name: INGRESS_HOST
              value: "http://<INGRESS_IP>/"
            - name: MICROSERVICE_PORT
              value: "7006"
          ports:
            - containerPort: 7006
          readinessProbe:
            httpGet:
              path: /stress/health
              port: 7006
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              cpu: "1m"
