apiVersion: v1
kind: Namespace
metadata:
  name: k8s-discord
---

apiVersion: v1
kind: Service
metadata:
  name: k8s-lb-stress
  namespace: k8s-discord
spec:
  selector:
    app: microservice-stress
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 7006
  type: LoadBalancer
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-stress
  namespace: k8s-discord
spec:
  replicas: 3
  selector:
    matchLabels:
      app: microservice-stress
  template:
    metadata:
      labels:
        app: microservice-stress
    spec:
      containers:
        - name: microservice-stress
          image: mystes123/python-stress-service:0.0.8
          env:
            - name: INGRESS_HOST
              value: "none"
            - name: MICROSERVICE_PORT
              value: "7006"
          ports:
            - containerPort: 7006
          readinessProbe:
            httpGet:
              path: /stress/health
              port: 7006
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              cpu: "1m"
