---
apiVersion: "autoscaling.k8s.io/v1"
kind: VerticalPodAutoscaler
metadata:
  name: vpa-stress
  namespace: k8s-discord
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: microservice-stress
  updatePolicy: 
    updateMode: Auto
  resourcePolicy:
    containerPolicies:
      - containerName: '*'
        controlledResources: 
          - cpu