apiVersion: v1
kind: Service
metadata:
  name: k8s-service-binary
  namespace: k8s-discord
spec:
  selector:
    app: microservice-binary
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-binary
  namespace: k8s-discord
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice-binary

  template:
    metadata:
      labels:
        app: microservice-binary
    spec:
      containers:
        - name: microservice-binary
          image: <DOCKER_USER>/microservices-binary:<TAG>
          env:
            - name: INGRESS_HOST
              value: "http://<INGRESS_HOST>/"
            - name: MICROSERVICE_PORT
              value: "8080"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /binary/health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5

