apiVersion: v1
kind: Service
metadata:
  name: k8s-service-math
  namespace: k8s-discord
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  selector:
    app: microservice-math
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 7003
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-math
  namespace: k8s-discord
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: microservice-math

  template:
    metadata:
      labels:
        app: microservice-math
    spec:
      containers:
        - name: microservice-math
          image: <DOCKER_USER>/microservices-math:<TAG>
          env:
            - name: INGRESS_HOST
              value: "http://<INGRESS_IP>/"
            - name: MICROSERVICE_PORT
              value: "7003"
          ports: 
            - containerPort: 7003
          readinessProbe:
            httpGet:
              path: /math/health
              port: 7003
            initialDelaySeconds: 5
            periodSeconds: 5
