apiVersion: v1
kind: Service
metadata:
  name: main-discord
spec:
  selector:
    app: discord-bot
  ports:
    - protocol: TCP
      port: 7000
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: discord-bot
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: discord-bot

  template:
    metadata:
      labels:
        app: discord-bot
    spec:
      containers:
        - name: discord-bot
          image: ticks/discord-bot:<TAG> 
          env:
            - name: DISCORD_TOKEN
              value: <SECRET_DISCORD_TOKEN>
            - name: SERVICE_PORT
              value: "7000"
          ports:
            - containerPort: 7000
              
        - name: microservice-echo
          image: ticks/microservices-echo:<TAG>
          env:
            - name: MICROSERVICE_PORT
              value: "7001"
          ports: 
            - containerPort: 7001
              
        - name: microservice-time
          image: ticks/microservices-time:<TAG>
          env:
            - name: MICROSERVICE_PORT
              value: "7002"
          ports: 
            - containerPort: 7002
              
        - name: microservice-math
          image: ticks/microservices-math:<TAG>
          env:
            - name: MICROSERVICE_PORT
              value: "7003"
          ports: 
            - containerPort: 7003
              